### ISSUE TITLE
Webcrypto for browser use (without losing node functionality)?

### ISSUE THREAD

**Issue by jbr** [rosek86/aes-cmac#3]
Hi, and thanks for this library! Would you be interested in a PR that uses [`one-webcrypto`](https://github.com/fission-suite/one-webcrypto) as a shim for the builtin subtle crypto apis on in browser and also node? I have a use case that needs to work in the browser and would prefer not to fork if possible

**Comment by rosek86** [comment]
Hi,

Sure, I’ve been thinking of adding web support so PR is much appreciated.

BR,
Krzysztof
